- name: first task
  hosts: local
  gather_facts: False
  roles:
    - first_role
  
  vars:
    - first_name: abdelali jadelmoula
  vars_files:
    - vars
  tasks:
    - debug: 
          msg: first task is {{first_name}}
       
    - debug:
         msg: my age is {{age}}

     
